### ISSUE TITLE
Advanced edition!

### ISSUE THREAD

**Issue by Ireliavent** [Vhati/ftl-profile-editor#56]
Hey!

I'm really enjoying your editor, works perfectly, flawless. I just have one question in mind thought... could you make it so it's possible to edit drones/weapons in advanced edition?

Thanks again! Let's hope you do not forget about this amazing project.

- Ireliavent

**Comment by DumbJoe** [comment]
> By editing Scrap you can get any System
By editing Cargo you can get any Weapon/Drone

>So, for all practical purposes (cough cheating cough), all major AE editing limitations are mitigated to the point of being irrelevant :)

Actually what I wanted to do was give my ship manned status for all systems that could be manned, except not have anyone in the room to "man" the system thus freeing my crew members for boarding or repairing systems and rooms. Can giving yourself scrap or editing the cargo do this? Nooo...... 

What about disabling enviornment and enemy ship abilities that peg your power or other systems down some notches? In an ION storm, I want to have full power to everything even in the storm. I also want to see the boss flagship's power distributions since they have an ability to disable my camera systems down to level 1.

There are other things that I would like to do when editing systems tab but of course that is not possible. I wanna have fun mucking around giving myself more reactor power than is possible even with the scrap; what if I want to give myself 999 power and then not worry about needing to turn off any power during an ION storm? 

What about editing stealth time? Have level 1 stealth system last 5 minutes instead of 5 seconds? Or give yourself more than level 4 shields, maybe level 10 shields making you almost impossible to beat(with the only thing that would be able to damage your ship are missile base weapons) 

What about editing weapon damage? Have a pegeasus missile do 100 damage instead of 1 instantly destroying the enemy craft with one missile assuming it hits and doesn't miss.

What about editing dodge and evasion? Give yourself 100% evasion and dodge and any missile and energy attacks always miss! You'll be a powerhouse with this mod!

What about giving yourself no cooldown for weapons or the weapon system giving you 100000000% recharge rate effectively giving yourself an instant no cool down for any weapon and have a faster fire rate weapon?

What about instant shield recharge? Or an Overshield that is so powerful that no weapons can damage it making you invulnerable to any and all attacks since attacks must destroy the shield to get to your shield and crew cant teleport to your ship because you have the overshield on.

How about giving your cremembers one hit kill ability? Your crew are so powerful that hitting one enemy cremember will kill them instantly giving you the win!

Or giving your crew member more health? There is a health mod I tried changing in the save editor but that didn't do anything. Put the value too high and you insta kill your crew members, but it too low and nothing happens or you damage your crew member mooting the point of giving them extra health points.... 

I could think of more things to screw around with the game to make it more fun but these are some of the ideas I had in mind.
