### ISSUE TITLE
Store

### ISSUE THREAD

**Issue by teepee2345** [Vhati/ftl-profile-editor#80]
Whenever i try to add a store to the map i cant edit it. i hit select store and spam-click the store and nothing happens. I am running version 25

**Comment by Vhati** [comment]
There was a silly typo that broke how the editor's GUI displays store shelves. Between this and the equally trivial projectile fix, I really need to release the next version.

At first I had been waiting for something more substantial to justify an update, then I kept getting distracted.  : )

**Comment by teepee2345** [comment]
You also might want to fix the problem of not being able to edit systems,
weapons and drones due to the editor treating every save game as an AE file

On Tuesday, March 15, 2016, Vhati <notifications@github.com> wrote:

> There was a silly typo that broke how the editor's GUI displays store
> shelves. Between this and the equally trivial projectile fix, I really need
> to release the next version.
>
> At first I had been waiting for something more substantial to justify an
> update, then I kept getting distracted. : )
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Vhati/ftl-profile-editor/issues/80#issuecomment-197105777>
>


-- 
From: Tyler Burns

**Comment by Vhati** [comment]
> You also might want to fix the problem of not being able to edit systems,
> weapons and drones due to the editor treating every save game as an AE file

Several interesting points of confusion.
* The "AE Content: true" bug you discovered was only cosmetic, when printed as text.
* Various features are disabled when opening a saved game created since FTL 1.5.4, due to the new format of the file itself.
* The DLC/"AE Content" checkbox swaps out the lists of available weapons/ships/etc in-game. No effect on the file format.
* The editor's GUI currently does not currently honor the DLC/"AE Content" flag. In most cases, for games with DLC disabled, this means the lists have extra choices which would crash FTL if chosen. (e.g., cargo) Some work has been done under the hood out of necessity, but this is not a limiting factor for other features. This part's actually not limited enough. More of an extra effort to protect users from themseves kinda thing  ; )

Projectiles and drones (specifically the drone pod things that float around) have the majority of remaining unknowns - they're volatile, short-lived, and lack visible stats, which hinders investigation.

Weapons embed projectiles as they prepare to fire. Systems embed weapons and drones. So they're all contaminated by uneditability. Plus the goofy rules governing power calculation and targeting, which are basically known in theory but tricky to implement.

Going over this reminds me of an workaround idea I had a while back though. Cutting power ship-wide to allow adding pristine unloaded weapons. Leaving users to power up again in-game.

**Comment by teepee2345** [comment]
Sounds like a good idea. I would think that you would be able to find stats
in game files

On Thursday, March 17, 2016, Vhati <notifications@github.com> wrote:

> You also might want to fix the problem of not being able to edit systems,
> weapons and drones due to the editor treating every save game as an AE file
>
> Several interesting points of confusion.
>
>    - The "AE Content: true" bug you discovered was only cosmetic, when
>    printed as text.
>    - Various features are disabled when opening a saved game created
>    since FTL 1.5.4, due to the new format of the file itself.
>    - The DLC/"AE Content" checkbox swaps out the lists of available
>    weapons/ships/etc in-game. No effect on the file format.
>    - The editor's GUI currently does not currently honor the DLC/"AE
>    Content" flag. In most cases, for games with DLC disabled, this means the
>    lists have extra choices which would crash FTL if chosen. (e.g., cargo)
>    Some work has been done under the hood out of necessity, but this is not a
>    limiting factor for other features. This part's actually not limited
>    enough. More of an extra effort to protect users from themseves kinda thing
>    ; )
>
> Projectiles and drones (specifically the drone pod things that float
> around) have the majority of remaining unknowns - they're volatile,
> short-lived, and lack visible stats, which hinders investigation.
>
> Weapons embed projectiles as they prepare to fire. Systems embed weapons
> and drones. So they're all contaminated by uneditability. Plus the goofy
> rules governing power calculation and targeting, which are basically known
> in theory but tricky to implement.
>
> Going over this reminds me of an workaround idea I had a while back
> though. Cutting power ship-wide to allow adding pristine unloaded weapons.
> Leaving users to power up again in-game.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Vhati/ftl-profile-editor/issues/80#issuecomment-197724293>
>


-- 
From: Tyler Burns

**Comment by Vhati** [comment]
>> they're volatile, short-lived, and lack visible stats, which hinders investigation.

> Sounds like a good idea. I would think that you would be able to find stats in game files

The files have numbers, with unknown meaning. I give them Greek labels. I can watch them change over time by saving repeatedly and using the editor to print a text summary. Some look like screen pixel coordinates. Some seem to count up/down. Some change in particular situations. Some are legitimately random.

Sometimes I use a hex editor to change the value and see what happens. If there were visible stats in-game, I could compare and find matching numbers, then see how FTL labeled the stat. I've dabbled in using CheatEngine to search/tweak the numbers live, without much success.

For instance, crew have a number that's frequently 100, which goes down when injured. FTL displays a health bar that makes the connection obvious when it drops to uncommon integers, like 31 or something.

That's how reverse engineering a saved game format goes. The old format had fewer volatile elements saved in it, making it easier to decipher.

**Comment by teepee2345** [comment]
Why updates? WHY!!!!


From: Tyler Burns

**Comment by Niels-NTG** [comment]
To make the game more awesome, that's why.

**Comment by teepee2345** [comment]
I also found that if I try to add either a quest marker or distress call to the map it doesn't work.

**Comment by Vhati** [comment]
Store editing has been fixed in v26.
