### ISSUE TITLE
Exception destroys savegame during write while fighting endgame boss

### ISSUE THREAD

**Issue by sonopard** [Vhati/ftl-profile-editor#92]
The resulting savegame was corrupted.

ERROR FTLFrame - Error saving game state ("continue.sav"). java.io.IOException: Unsupported extended projectile info: EmptyProjectileInfo
	at net.blerf.ftl.parser.SavedGameParser.writeProjectile(SavedGameParser.java:1824)
	at net.blerf.ftl.parser.SavedGameParser.writeZeus(SavedGameParser.java:9278)
	at net.blerf.ftl.parser.SavedGameParser.writeSavedGame(SavedGameParser.java:408)
	at net.blerf.ftl.ui.FTLFrame$12.actionPerformed(FTLFrame.java:938)

[dump.txt](https://github.com/Vhati/ftl-profile-editor/files/610609/dump.txt)

[continue.sav.zip](https://github.com/Vhati/ftl-profile-editor/files/610611/continue.sav.zip)

**Comment by Malanius** [comment]
Hello,
since this is open for some time, I'll quote @Vhati  from #93:

> Avoid saves made during combat. There's a bug in the editor that causes corruption when writing a saved game that has certain projectiles/asteroids on the screen.

According to the exception, 
`java.io.IOException: Unsupported extended projectile info: EmptyProjectileInfo`,
this is exactly what happened to you.

As far as I remember (I didn't play FTL for more than a year), there should be a backup of the save file in the same folder.

I hope it helps.

**Comment by Vhati** [comment]
@Malanius
Yep, thanks.

**Comment by Vhati** [comment]
Fixed in v26.
