### ISSUE TITLE
Advanced Edition content is enabled while disabled

### ISSUE THREAD

**Issue by koumakpet** [Vhati/ftl-profile-editor#97]
In Saved Game Dump it says I have enabled AE content (AE Content:              true) so I can't edit many things but I don't I created game with disabled AE content and when I open game it says: AE Content: Disabled so what the hell is going on here ?

**Comment by Vhati** [comment]
Per the readme...
>FTL 1.01-1.03.3: "prof.sav" and "continue.sav" files are fully editable.
>FTL 1.5.4-1.5.13: "ae_prof.sav" is fully editable.
>FTL 1.5.4-1.5.13: "continue.sav" is only partially editable.

Early versions of the game were simply called FTL. That savedgame format was fully reverse engineered. At the time, you could only save when not in combat, so there was less volitile information to store.

Then came FTL: Advanced Edition. It changed the savedgame format, adding lots of variables that were never understood, and thus unsafe to edit. That format is *always* used when FTL:AE saves the state of the game.

There's also an in-game setting to toggle "AE Content". This DOES NOT affect the savedgame format. What it does it restrict the items/enemies/etc that will be encountered in the campaign. It tells the game not to spawn certain races for example. The editor will still be unable to edit systems, because the format describes systems differently since v1.5.4.

Note: if AE Content is disabled, the game will crash if it loads a modified savedgame which includes those things. Technically the editor could be heavily rewritten to protect users from themselves - it wasn't worth the effort, so you'll still see all the races, for example (just don't add them in, when AE Content is disabled).
